# Generated by Django 4.2.1 on 2023-05-27 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_alter_event_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="likes",
            new_name="liked_by",
        ),
        migrations.RemoveField(
            model_name="user",
            name="events",
        ),
        migrations.AddField(
            model_name="user",
            name="liked_events",
            field=models.ManyToManyField(
                blank=True, related_name="liked_events", to="events.event"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
