# Generated by Django 4.2.1 on 2023-05-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_rename_likes_event_liked_by_remove_user_events_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="liked_by",
        ),
        migrations.AddField(
            model_name="event",
            name="is_liked",
            field=models.BooleanField(default=False),
        ),
    ]
